apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-deploy
  labels:
    name: meal-deploy
    app: meal-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: meal-pod
      app: meal-app
  template:
    metadata:
      name: meal-pod
      labels:
        name: meal-pod
        app: meal-app
    spec:
      containers:
      - name: meal-website
        image: damola12345/meal-website:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80