apiVersion: v1
kind: Service
metadata:
  name: meal-service
  labels:
    name: meal-service
    app: meal-app
spec:
  selector:
    name: meal-pod
    app: meal-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31225